services:
    sonata.admin.guest:
        class: App\AdminBundle\Admin\GuestAdmin
        arguments: [~, App\CoreBundle\Entity\Guest, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: 'Guests'
              label: 'Guests'
              icon: '<i class="fa fa-car"></i>'
              on_top: true
