# App Bundles
_front_end:
    resource: "@AppFrontEndBundle/Resources/config/routing.yml"

_api:
    resource: "@AppApiBundle/Resources/config/routing.yml"
    prefix: "/api"
    options:
        expose: true

_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix: "/%admin_directory%"
    options:
        expose: true

# Other bundles
_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /%admin_directory%

_sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: "/%admin_directory%/resetting"

# Always keep default route as a last one
# Default route for Front-end, prevents 404 Not found for Front-end routes.
# Ignores admin and api directories
default:
    path: "/{path}"
    defaults:
        _controller: AppFrontEndBundle:Index:index
    requirements:
        path: "^(?!%admin_directory%|api).+"