security:
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN_GUEST_LIST
            - ROLE_SONATA_ADMIN_GUEST_VIEW
            - ROLE_SONATA_ADMIN_GUEST_EXPORT
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_SELF
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    access_decision_manager:
        strategy: unanimous

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 13

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/%admin_directory%(.*)
            context: user
            form_login:
                provider:       fos_userbundle
                login_path:     /%admin_directory%/login
                use_forward:    false
                check_path:     /%admin_directory%/login_check
                failure_path:   null
                always_use_default_target_path: true
                default_target_path: /%admin_directory%/dashboard
            logout:
                path: /%admin_directory%/logout
            anonymous: ~
            switch_user: true

        api:
            pattern: ^/api(.*)
            anonymous: ~
            stateless: ~

    access_control:
        - { path: ^/%admin_directory%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_directory%/(.*), role: ROLE_ADMIN }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/(.*), role: IS_AUTHENTICATED_FULLY }